#!/bin/bash
#########################################################
#
# name: _mmenu (multimenu)
# author: Tomasz Winiarski
# date: 20200123
# desc: chooses appropriate menu depending on environment
#       (X, term, console) and available apps
#       TODO: "themes"
# usage: see helpMsg below or use `_mmenu --help`
#
########################################################
function helpMsg {
  cat << 'HELPMSG'

    _mmenu -- chooses appropriate menu

    USAGE:

    _mmenu [options] --file|-f <filename>

    _mmenu [options] --items|-i <item1> <item2> .. <item n>

   stdin | _mmenu [options]

   --menu-app|-a (dmenu|slmenu|climenu)
     :force use of a given app to display menu.
      Comp. -g
   
   --file|-f <filename>
     :read items to be displayed from a file.
   
   --gui-if-possible|-g
     :force use of gui menu app (dmenu) if in X,
      even if stdout is term.
   
   --help|-h
     :display this message and exit.
   
   --items|-i <item1> <item2> .. <item n>
     :read items to be displayed from cliargs.
      Must be the last option.

HELPMSG
}

declare items=()
declare mApp="";

while : ; do

  case "$1" in
    --menu-app|-a) mApp="$2" ; shift 2 ;;
    --file|-f) 
              while read line; do
                items+=("${line}")
              done < "$2" 
              shift 2
    ;;
    --gui-if-possible|-g) shift ; [[ $DISPLAY ]] && [[ $(which dmenu) ]] && mApp="dmenu" || err "no dmenu in $PATH";;
    --help|-h) helpMsg && exit 0 ;;
    --items|-i) shift ; items=("${@}"); break ;;
    '') break;;
    *)
       err "Unknown option ${1}"
       helpMsg
       exit 129
    ;;
  esac

done

if [[ ! $mApp ]] ; then
  if [[ -t 1 ]] ; then
    [[ $(which slmenu) ]] && mApp="slmenu" || mApp="climenu" # created with bash `select`
  else
    [[ $(which dmenu) ]] && mApp="dmenu" || err "no dmenu in $PATH"
  fi
fi

if [[ ${#items[@]} == 0 ]]; then
  echo "reading from pipe"
  if [[ -p /dev/stdin ]]; then
    while IFS= read line; do
      items+=("${line}")
    done
  else
    err "No items to display"
    helpMsg
    exit 130
  fi
fi

case $mApp in 
  dmenu) printf '%s\n' "${items[@]}" | dmenu -l 10 ;;
  slmenu) printf '%s\n' "${items[@]}" | slmenu ;;
  climenu) 
          select item in "${items[@]}"; do
            printf '%s\n' "${item}"
            break
          done
  ;;
esac

exit 0

#vim: ft=sh ts=2 tw=2
